In [1]:
#1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
#2. Create a vector with values ranging from 10 to 49.
import numpy as np

vector = np.arange(10,50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np

matrix = np.arange(9)

my_matrix = matrix.reshape(3,3)

print(my_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np

my_array = np.array([1,2,0,0,4,0])

non_zeroindices = np.nonzero(my_array)

print([non_zeroindices])

[(array([0, 1, 4]),)]


In [5]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np

random_array = np.random.rand(10,10)

max_value = np.max(random_array)
min_value = np.min(random_array)

print(max_value)
print(min_value)


0.9998178128037962
0.014308872043295118


In [6]:
#6. Create a random vector of size 30 and find the mean value.
import numpy as np

random_vector = np.random.rand(30)

mean_value = np.mean(random_vector)

print(mean_value)

0.5481570185818269
